/**
 * @license
 * Copyright 2018 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

/* eslint-disable max-len */

const fcpRelevantAudits = [
  'server-response-time',
  'render-blocking-resources',
  'redirects',
  'critical-request-chains',
  'uses-text-compression',
  'uses-rel-preconnect',
  'uses-rel-preload',
  'font-display',
  'unminified-javascript',
  'unminified-css',
  'unused-css-rules',
];

const lcpRelevantAudits = [
  ...fcpRelevantAudits,
  'largest-contentful-paint-element',
  'prioritize-lcp-image',
  'unused-javascript',
  'efficient-animated-content',
  'total-byte-weight',
  'lcp-lazy-loaded',
];

const tbtRelevantAudits = [
  'long-tasks',
  'third-party-summary',
  'third-party-facades',
  'bootup-time',
  'mainthread-work-breakdown',
  'dom-size',
  'duplicated-javascript',
  'legacy-javascript',
  'viewport',
];

const clsRelevantAudits = [
  'layout-shift-elements',
  'layout-shifts',
  'non-composited-animations',
  'unsized-images',
  // 'preload-fonts', // actually in BP, rather than perf
];

const inpRelevantAudits = ['work-during-interaction'];

const metricsToAudits = {
  fcpRelevantAudits,
  lcpRelevantAudits,
  tbtRelevantAudits,
  clsRelevantAudits,
  inpRelevantAudits,
};

const defaultSettings = {
  output: 'json',
  maxWaitForFcp: 30 * 1000,
  maxWaitForLoad: 45 * 1000,
  pauseAfterFcpMs: 1000,
  pauseAfterLoadMs: 1000,
  networkQuietThresholdMs: 1000,
  cpuQuietThresholdMs: 1000,

  auditMode: false,
  gatherMode: false,
  clearStorageTypes: [
    'file_systems',
    'shader_cache',
    'service_workers',
    'cache_storage',
  ],
  disableStorageReset: false,
  debugNavigation: false,
  channel: 'node',
  usePassiveGathering: false,
  disableFullPageScreenshot: true,
  skipAboutBlank: false,
  blankPage: 'about:blank',
  ignoreStatusCode: false,

  // the following settings have no defaults but we still want ensure that `key in settings`
  // in config will work in a typechecked way
  budgets: null,
  locale: 'en-US', // actual default determined by Config using lib/i18n
  blockedUrlPatterns: null,
  additionalTraceCategories: null,
  extraHeaders: null,
  precomputedLanternData: null,
  onlyAudits: null,
  onlyCategories: null,
  skipAudits: null,
};

const UIStrings = {
  /** Title of the Performance category of audits. Equivalent to 'Web performance', this term is inclusive of all web page speed and loading optimization topics. Also used as a label of a score gauge; try to limit to 20 characters. */
  performanceCategoryTitle: 'Performance',

  metricGroupTitle: 'Metrics',
};

/** @type {LH.Config} */
const defaultConfig = {
  settings: defaultSettings,
  artifacts: [
    // Artifacts which can be depended on come first.
    { id: 'DevtoolsLog', gatherer: 'devtools-log' },
    { id: 'Trace', gatherer: 'trace' },
    { id: 'RootCauses', gatherer: 'root-causes' },

    // { id: 'Accessibility', gatherer: 'accessibility' },
    // { id: 'AnchorElements', gatherer: 'anchor-elements' },
    // { id: 'CacheContents', gatherer: 'cache-contents' },
    // { id: 'ConsoleMessages', gatherer: 'console-messages' },
    // { id: 'CSSUsage', gatherer: 'css-usage' },
    // { id: 'Doctype', gatherer: 'dobetterweb/doctype' },
    // { id: 'DOMStats', gatherer: 'dobetterweb/domstats' },
    // { id: 'EmbeddedContent', gatherer: 'seo/embedded-content' },
    // { id: 'FontSize', gatherer: 'seo/font-size' },
    // { id: 'Inputs', gatherer: 'inputs' },
    // { id: 'GlobalListeners', gatherer: 'global-listeners' },
    // { id: 'IFrameElements', gatherer: 'iframe-elements' },
    // { id: 'ImageElements', gatherer: 'image-elements' },
    // { id: 'InstallabilityErrors', gatherer: 'installability-errors' },
    // { id: 'InspectorIssues', gatherer: 'inspector-issues' },
    // { id: 'JsUsage', gatherer: 'js-usage' },
    // { id: 'LinkElements', gatherer: 'link-elements' },
    // { id: 'MainDocumentContent', gatherer: 'main-document-content' },
    // { id: 'MetaElements', gatherer: 'meta-elements' },
    // { id: 'NetworkUserAgent', gatherer: 'network-user-agent' },
    // { id: 'OptimizedImages', gatherer: 'dobetterweb/optimized-images' },
    // { id: 'ResponseCompression', gatherer: 'dobetterweb/response-compression' },
    // { id: 'RobotsTxt', gatherer: 'seo/robots-txt' },
    // { id: 'ServiceWorker', gatherer: 'service-worker' },
    // { id: 'ScriptElements', gatherer: 'script-elements' },
    // { id: 'Scripts', gatherer: 'scripts' },
    // { id: 'SourceMaps', gatherer: 'source-maps' },
    // { id: 'Stacks', gatherer: 'stacks' },
    // {
    //   id: 'TagsBlockingFirstPaint',
    //   gatherer: 'dobetterweb/tags-blocking-first-paint',
    // },
    // { id: 'TapTargets', gatherer: 'seo/tap-targets' },
    // { id: 'TraceElements', gatherer: 'trace-elements' },
    // { id: 'ViewportDimensions', gatherer: 'viewport-dimensions' },
    // { id: 'WebAppManifest', gatherer: 'web-app-manifest' },

    // Artifact copies are renamed for compatibility with legacy artifacts.
    // { id: 'devtoolsLogs', gatherer: 'devtools-log-compat' },
    // { id: 'traces', gatherer: 'trace-compat' },

    // FullPageScreenshot comes at the end so all other node analysis is captured.
    // {id: 'FullPageScreenshot', gatherer: 'full-page-screenshot'},

    // BFCacheFailures comes at the very end because it can perform a page navigation.
    // {id: 'BFCacheFailures', gatherer: 'bf-cache-failures'},
  ],
  audits: [
    'is-on-https',
    'viewport',
    'metrics/first-contentful-paint',
    'metrics/largest-contentful-paint',
    'metrics/first-meaningful-paint',
    'metrics/speed-index',
    // 'screenshot-thumbnails',
    // 'final-screenshot',
    'metrics/total-blocking-time',
    'metrics/max-potential-fid',
    'metrics/cumulative-layout-shift',
    'metrics/interaction-to-next-paint',
    // 'errors-in-console',
    // 'server-response-time',
    // 'metrics/interactive',
    // 'user-timings',
    // 'critical-request-chains',
    // 'redirects',
    // 'installable-manifest',
    // 'splash-screen',
    // 'themed-omnibox',
    // 'maskable-icon',
    // 'content-width',
    // 'image-aspect-ratio',
    // 'image-size-responsive',
    // 'preload-fonts',
    // 'deprecations',
    // 'third-party-cookies',
    // 'mainthread-work-breakdown',
    // 'bootup-time',
    // 'uses-rel-preload',
    // 'uses-rel-preconnect',
    // 'font-display',
    // 'diagnostics',
    // 'network-requests',
    // 'network-rtt',
    // 'network-server-latency',
    // 'main-thread-tasks',
    // 'metrics',
    // 'performance-budget',
    // 'timing-budget',
    // 'resource-summary',
    // 'third-party-summary',
    // 'third-party-facades',
    // 'largest-contentful-paint-element',
    // 'lcp-lazy-loaded',
    // 'layout-shift-elements',
    // 'layout-shifts',
    // 'long-tasks',
    // 'no-unload-listeners',
    // 'non-composited-animations',
    // 'unsized-images',
    // 'valid-source-maps',
    // 'prioritize-lcp-image',
    // 'csp-xss',
    // 'script-treemap-data',
    // 'manual/pwa-cross-browser',
    // 'manual/pwa-page-transitions',
    // 'manual/pwa-each-page-has-url',
    // 'accessibility/accesskeys',
    // 'accessibility/aria-allowed-attr',
    // 'accessibility/aria-allowed-role',
    // 'accessibility/aria-command-name',
    // 'accessibility/aria-dialog-name',
    // 'accessibility/aria-hidden-body',
    // 'accessibility/aria-hidden-focus',
    // 'accessibility/aria-input-field-name',
    // 'accessibility/aria-meter-name',
    // 'accessibility/aria-progressbar-name',
    // 'accessibility/aria-required-attr',
    // 'accessibility/aria-required-children',
    // 'accessibility/aria-required-parent',
    // 'accessibility/aria-roles',
    // 'accessibility/aria-text',
    // 'accessibility/aria-toggle-field-name',
    // 'accessibility/aria-tooltip-name',
    // 'accessibility/aria-treeitem-name',
    // 'accessibility/aria-valid-attr-value',
    // 'accessibility/aria-valid-attr',
    // 'accessibility/button-name',
    // 'accessibility/bypass',
    // 'accessibility/color-contrast',
    // 'accessibility/definition-list',
    // 'accessibility/dlitem',
    // 'accessibility/document-title',
    // 'accessibility/duplicate-id-active',
    // 'accessibility/duplicate-id-aria',
    // 'accessibility/empty-heading',
    // 'accessibility/form-field-multiple-labels',
    // 'accessibility/frame-title',
    // 'accessibility/heading-order',
    // 'accessibility/html-has-lang',
    // 'accessibility/html-lang-valid',
    // 'accessibility/html-xml-lang-mismatch',
    // 'accessibility/identical-links-same-purpose',
    // 'accessibility/image-alt',
    // 'accessibility/image-redundant-alt',
    // 'accessibility/input-button-name',
    // 'accessibility/input-image-alt',
    // 'accessibility/label-content-name-mismatch',
    // 'accessibility/label',
    // 'accessibility/landmark-one-main',
    // 'accessibility/link-name',
    // 'accessibility/link-in-text-block',
    // 'accessibility/list',
    // 'accessibility/listitem',
    // 'accessibility/meta-refresh',
    // 'accessibility/meta-viewport',
    // 'accessibility/object-alt',
    // 'accessibility/select-name',
    // 'accessibility/skip-link',
    // 'accessibility/tabindex',
    // 'accessibility/table-duplicate-name',
    // 'accessibility/table-fake-caption',
    // 'accessibility/target-size',
    // 'accessibility/td-has-header',
    // 'accessibility/td-headers-attr',
    // 'accessibility/th-has-data-cells',
    // 'accessibility/valid-lang',
    // 'accessibility/video-caption',
    // 'accessibility/manual/custom-controls-labels',
    // 'accessibility/manual/custom-controls-roles',
    // 'accessibility/manual/focus-traps',
    // 'accessibility/manual/focusable-controls',
    // 'accessibility/manual/interactive-element-affordance',
    // 'accessibility/manual/logical-tab-order',
    // 'accessibility/manual/managed-focus',
    // 'accessibility/manual/offscreen-content-hidden',
    // 'accessibility/manual/use-landmarks',
    // 'accessibility/manual/visual-order-follows-dom',
    // 'byte-efficiency/uses-long-cache-ttl',
    // 'byte-efficiency/total-byte-weight',
    // 'byte-efficiency/offscreen-images',
    // 'byte-efficiency/render-blocking-resources',
    // 'byte-efficiency/unminified-css',
    // 'byte-efficiency/unminified-javascript',
    // 'byte-efficiency/unused-css-rules',
    // 'byte-efficiency/unused-javascript',
    // 'byte-efficiency/modern-image-formats',
    // 'byte-efficiency/uses-optimized-images',
    // 'byte-efficiency/uses-text-compression',
    // 'byte-efficiency/uses-responsive-images',
    // 'byte-efficiency/efficient-animated-content',
    // 'byte-efficiency/duplicated-javascript',
    // 'byte-efficiency/legacy-javascript',
    // 'byte-efficiency/uses-responsive-images-snapshot',
    // 'dobetterweb/doctype',
    // 'dobetterweb/charset',
    // 'dobetterweb/dom-size',
    // 'dobetterweb/geolocation-on-start',
    // 'dobetterweb/inspector-issues',
    // 'dobetterweb/no-document-write',
    // 'dobetterweb/js-libraries',
    // 'dobetterweb/notification-on-start',
    // 'dobetterweb/paste-preventing-inputs',
    // 'dobetterweb/uses-http2',
    // 'dobetterweb/uses-passive-event-listeners',
    // 'seo/meta-description',
    // 'seo/http-status-code',
    // 'seo/font-size',
    // 'seo/link-text',
    // 'seo/crawlable-anchors',
    // 'seo/is-crawlable',
    // 'seo/robots-txt',
    // 'seo/tap-targets',
    // 'seo/hreflang',
    // 'seo/plugins',
    // 'seo/canonical',
    // 'seo/manual/structured-data',
    // 'work-during-interaction',
    // 'bf-cache',
  ],
  groups: {
    metrics: {
      title: 'Metrics',
    },

    // Group for audits that should not be displayed.
    hidden: { title: '' },
  },
  categories: {
    performance: {
      title: 'performance',
      supportedModes: ['navigation'],
      auditRefs: [
        {
          id: 'first-contentful-paint',
          weight: 10,
          group: 'metrics',
          acronym: 'FCP',
          relevantAudits: metricsToAudits.fcpRelevantAudits,
        },
        {
          id: 'largest-contentful-paint',
          weight: 25,
          group: 'metrics',
          acronym: 'LCP',
          relevantAudits: metricsToAudits.lcpRelevantAudits,
        },
        {
          id: 'total-blocking-time',
          weight: 30,
          group: 'metrics',
          acronym: 'TBT',
          relevantAudits: metricsToAudits.tbtRelevantAudits,
        },
        {
          id: 'cumulative-layout-shift',
          weight: 25,
          group: 'metrics',
          acronym: 'CLS',
          relevantAudits: metricsToAudits.clsRelevantAudits,
        },
        { id: 'speed-index', weight: 10, group: 'metrics', acronym: 'SI' },
        // {
        //   id: 'interaction-to-next-paint',
        //   weight: 0,
        //   group: 'metrics',
        //   acronym: 'INP',
        //   relevantAudits: metricsToAudits.inpRelevantAudits,
        // },

        // These are our "invisible" metrics. Not displayed, but still in the LHR.
        { id: 'interactive', weight: 0, group: 'hidden', acronym: 'TTI' },
        // { id: 'max-potential-fid', weight: 0, group: 'hidden' },
        {
          id: 'first-meaningful-paint',
          weight: 0,
          acronym: 'FMP',
          group: 'hidden',
        },

        // These audits will be put in "load-opportunities" or "diagnostics" based on their details type.
        // { id: 'render-blocking-resources', weight: 0 },
        // { id: 'uses-responsive-images', weight: 0 },
        // { id: 'offscreen-images', weight: 0 },
        // { id: 'unminified-css', weight: 0 },
        // { id: 'unminified-javascript', weight: 0 },
        // { id: 'unused-css-rules', weight: 0 },
        // { id: 'unused-javascript', weight: 0 },
        // { id: 'uses-optimized-images', weight: 0 },
        // { id: 'modern-image-formats', weight: 0 },
        // { id: 'uses-text-compression', weight: 0 },
        // { id: 'uses-rel-preconnect', weight: 0 },
        // { id: 'server-response-time', weight: 0 },
        // { id: 'redirects', weight: 0 },
        // { id: 'uses-rel-preload', weight: 0 },
        // { id: 'uses-http2', weight: 0 },
        // { id: 'efficient-animated-content', weight: 0 },
        // { id: 'duplicated-javascript', weight: 0 },
        // { id: 'legacy-javascript', weight: 0 },
        // { id: 'prioritize-lcp-image', weight: 0 },
        // { id: 'total-byte-weight', weight: 0 },
        // { id: 'uses-long-cache-ttl', weight: 0 },
        // { id: 'dom-size', weight: 0 },
        // { id: 'critical-request-chains', weight: 0 },
        // { id: 'user-timings', weight: 0 },
        // { id: 'bootup-time', weight: 0 },
        // { id: 'mainthread-work-breakdown', weight: 0 },
        // { id: 'font-display', weight: 0 },
        // { id: 'third-party-summary', weight: 0 },
        // { id: 'third-party-facades', weight: 0 },
        // { id: 'largest-contentful-paint-element', weight: 0 },
        // { id: 'lcp-lazy-loaded', weight: 0 },
        // { id: 'layout-shifts', weight: 0 },
        // { id: 'uses-passive-event-listeners', weight: 0 },
        // { id: 'no-document-write', weight: 0 },
        // { id: 'long-tasks', weight: 0 },
        // { id: 'non-composited-animations', weight: 0 },
        // { id: 'unsized-images', weight: 0 },
        // { id: 'viewport', weight: 0 },
        // { id: 'uses-responsive-images-snapshot', weight: 0 },
        // { id: 'work-during-interaction', weight: 0 },
        // { id: 'bf-cache', weight: 0 },

        // Budget audits.
        // { id: 'performance-budget', weight: 0, group: 'budgets' },
        // { id: 'timing-budget', weight: 0, group: 'budgets' },

        // Audits past this point contain useful data but are not displayed with other audits.
        // { id: 'network-requests', weight: 0, group: 'hidden' },
        // { id: 'network-rtt', weight: 0, group: 'hidden' },
        // { id: 'network-server-latency', weight: 0, group: 'hidden' },
        // { id: 'main-thread-tasks', weight: 0, group: 'hidden' },
        // { id: 'diagnostics', weight: 0, group: 'hidden' },
        // { id: 'metrics', weight: 0, group: 'hidden' },
        // { id: 'screenshot-thumbnails', weight: 0, group: 'hidden' },
        // { id: 'final-screenshot', weight: 0, group: 'hidden' },
        // { id: 'script-treemap-data', weight: 0, group: 'hidden' },
        // { id: 'resource-summary', weight: 0, group: 'hidden' },
        // { id: 'layout-shift-elements', weight: 0, group: 'hidden' },
      ],
    },
  },
};

// Use `defineProperty` so that the strings are accesible from original but ignored when we copy it
// Object.defineProperty(defaultConfig, 'UIStrings', {
//   enumerable: false,
//   get: () => UIStrings,
// });

export default defaultConfig;
