-- CreateTable
CREATE TABLE "Analyze" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "url" TEXT NOT NULL,
    "firstContentfulPaint" REAL NOT NULL,
    "largestContentfulPaint" REAL NOT NULL,
    "firstMeaningfulPaint" REAL NOT NULL,
    "speedIndex" REAL NOT NULL,
    "totalBlockingTime" REAL NOT NULL,
    "maxPotentialFid" REAL NOT NULL,
    "cumulativeLayoutShift" REAL NOT NULL,
    "serverResponseTime" REAL NOT NULL,
    "timeToInteractive" REAL NOT NULL,
    "metrics" REAL NOT NULL,
    "analyzeScore" REAL NOT NULL,
    "weightFirstContentfulPaint" REAL NOT NULL,
    "weightLargestContentfulPaint" REAL NOT NULL,
    "weightFirstMeaningfulPaint" REAL NOT NULL,
    "weightSpeedIndex" REAL NOT NULL,
    "weightTotalBlockingTime" REAL NOT NULL,
    "weightMaxPotentialFid" REAL NOT NULL,
    "weightCumulativeLayoutShift" REAL NOT NULL,
    "weightServerResponseTime" REAL NOT NULL,
    "weightTimeToInteractive" REAL NOT NULL,
    "weightMetrics" REAL NOT NULL,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL
);
